#!/bin/bash

sbt elasticsearchUtil/clean elasticsearchUtil/compile elasticsearchUtil/publishSigned sonatypeRelease
sbt elasticsearchClientBinary/clean elasticsearchClientBinary/compile elasticsearchClientBinary/publishSigned sonatypeRelease
